name: 'Cache compiled assets'
inputs:
  failed-on-cache-miss:
    required: false
    default: false
  restore-only:
    required: false
    default: false
outputs:
  cache-hit:
    value: ${{ steps.cache-hit.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
  - run: echo 'restore-only="/restore"' >> $GITHUB_OUTPUT
    shell: bash
    if: inputs.restore-only == true
    id: restore-only
  - uses: "actions/cache${{ steps.restore-only.outputs.restore-only }}@v3"
    id: precompiled-asset
    with:
      fail-on-cache-miss: ${{ inputs.failed-on-cache-miss }}
      path: |
        public/assets
        public/packs-test
        tmp/cache/webpacker
      key: ${{ runner.os }}-precompiled-assets-${{ hashFiles('app/assets/**', 'app/javascript/**', 'config/webpack/**', 'config/webpacker.yml', '**/package.json', '**/yarn.lock', '**/babel.config.js') }}
      restore-keys: ${{ runner.os }}-precompiled-assets-
  - run: echo 'cache-hit=${{ steps.precompiled-asset.outputs.cache-hit }}' >> $GITHUB_OUTPUT
    shell: bash
    id: cache-hit
