name: 'Cache compiled assets'
inputs:
  failed-on-cache-miss:
    required: false
    default: false
  restore-only:
    required: false
    default: false
outputs:
  cache-hit:
    value: ${{ steps.random-number-generator.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
  - uses: actions/cache@v3
    id: precompiled-asset
    with:
      fail-on-cache-miss: ${{ inputs.failed-on-cache-miss }}
      path: |
        public/assets
        public/packs-test
        tmp/cache/webpacker
      key: ${{ runner.os }}-precompiled-assets-${{ hashFiles('app/assets/**', 'app/javascript/**', 'config/webpack/**', 'config/webpacker.yml', '**/package.json', '**/yarn.lock', '**/babel.config.js') }}
      restore-keys: ${{ runner.os }}-precompiled-assets-
  - id: random-number-generator
    run: echo 'cache-hit=${{ steps.precompiled-asset.outputs.cache-hit }}' >> $GITHUB_OUTPUT
    shell: bash
