codecov:
  require_ci_to_pass: no
  notify:
    wait_for_ci: no
    # after_n_builds: 2
ignore:
  - "vendor"
  - "bin"
  - "**/*.svg"
  - "lib/sitemap_generator"
  - "lib/generators"
coverage:
  status:
    patch: 90%
flag_management:
  default_rules:
    carryforward: true
    # statuses:
    #   - type: project
    #     target: auto
    #     threshold: 1%
