codecov:
  ci:
    - "!buildkite"
  require_ci_to_pass: no
  notify:
    wait_for_ci: no
ignore:
  - "vendor"
  - "bin"
  - "**/*.svg"
  - "lib/sitemap_generator"
  - "lib/generators"
coverage:
  status:
    patch:
      default:
        target: 90%
flag_management:
  default_rules:
    carryforward: true
    # statuses:
    #   - type: project
    #     target: auto
    #     threshold: 1%
