---
like:
  position: 1
  name: Like
  icon: twemoji/sparkle-heart
readinglist:
  position: 5
  icon: save
  published: false
lightbulb:
  position: 2
  icon: twemoji/bulb
rocket:
  position: 3
  icon: twemoji/rocket
unicorn:
  position: 4
  name: Unicorn
  icon: multi-unicorn
raised_hands:
  position: 5
  icon: twemoji/raised_hands
tada:
  position: 6
  icon: twemoji/tada
thumbsup:
  privileged: true
  score: 5.0
thumbsdown:
  privileged: true
  score: -10.0
vomit:
  privileged: true
  name: Vomit
  score: -50.0
thinking:
  published: false
hands:
  published: false
