version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    commit_message:
      prefix: "[skip travis]"
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "weekly"
    commit_message:
      prefix: "[skip travis]"