name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    RAILS_ENV: test
    NODE_ENV: test
    DATABASE_URL: postgres://postgres:postgres@localhost:5432/Forem_prod_test
    DATABASE_NAME: Forem_prod_test

jobs:
  bundle_install:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

  yarn_install:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --frozen-lock

  assets_precompile:
    runs-on: ubuntu-latest
    needs:
      - bundle_install
      - yarn_install
    timeout-minutes: 15
    env:
      RAILS_ENV: test
      NODE_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/Forem_prod_test
      DATABASE_NAME: Forem_prod_test
      APP_PROTOCOL: http://
      APP_DOMAIN: localhost:3000
      HEROKU_APP_URL: practicaldev.herokuapp.com
      SECRET_KEY_BASE: dummydummydummy
      GITHUB_KEY: dummy
      GITHUB_SECRET: dummy
      KNAPSACK_PRO_FIXED_QUEUE_SPLIT: true

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Cache node_modules
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-modules-
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --immutable-cache
      - name: Cache public/assets
        uses: actions/cache@v3
        with:
          path: |
            public/assets
            public/packs-test
          key: ${{ runner.os }}-assets_precompile
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rails assets:precompile
      - run: yarn run postcss
      - run: bin/test-console-check

  Jest:
    runs-on: ubuntu-latest
    needs:
      - yarn_install
    timeout-minutes: 10
    env:
      RAILS_ENV: test
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v3
      - name: Cache node_modules
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-modules-
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn lint:frontend
      - run: yarn test --colors --ci --reporters=jest-junit
      - name: Upload test results to BuildPulse for flaky test detection
        if: '!cancelled()' # Run this step even when the tests fail. Skip if the workflow is cancelled.
        uses: Workshop64/buildpulse-action@master
        with:
          account: ${{ secrets.BUILDPULSE_ACCOUNT }}
          repository: ${{ secrets.BUILDPULSE_REPOSITORY }}
          path: junit.xml
          key: ${{ secrets.BUILDPULSE_ACCESS_KEY_ID }}
          secret: ${{ secrets.BUILDPULSE_SECRET_ACCESS_KEY }}
      - uses: codecov/codecov-action@v3
        with:
          flags: javascript
      - run: yarn build-storybook

  RSpec:
    runs-on: ubuntu-latest
    needs:
      - bundle_install
      - yarn_install
    timeout-minutes: 15
    env:
      COVERAGE: true
      RAILS_ENV: test
      KNAPSACK_PRO_CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
      KNAPSACK_PRO_CI_NODE_INDEX: ${{ matrix.ci_node_index }}
      KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC: ${{ secrets.KNAPSACK_PRO_TEST_SUITE_TOKEN_RSPEC }}
      KNAPSACK_PRO_FIXED_QUEUE_SPLIT: true
      DATABASE_URL_TEST: postgres://postgres:postgres@localhost:5432/Forem_test
      DATABASE_NAME_TEST: Forem_test

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
      redis:
        image: redis
        ports:
          - 6379:6379

    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [9]
        ci_node_index: [0, 1, 2, 3, 4, 5, 6, 7, 8]

    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-modules-
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rails db:test:prepare
      - name: RSpec
        run: bin/knapsack_pro_rspec
      - uses: codecov/codecov-action@v3
        with:
          flags: ruby
      - name: Upload test results to BuildPulse for flaky test detection
        if: '!cancelled()' # Run this step even when the tests fail. Skip if the workflow is cancelled.
        uses: Workshop64/buildpulse-action@master
        with:
          account: ${{ secrets.BUILDPULSE_ACCOUNT }}
          repository: ${{ secrets.BUILDPULSE_REPOSITORY }}
          path: tmp/rspec_final_results.xml
          key: ${{ secrets.BUILDPULSE_ACCESS_KEY_ID }}
          secret: ${{ secrets.BUILDPULSE_SECRET_ACCESS_KEY }}
